defmodule LumenViae.Repo.Migrations.AddArtworkToMysteries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:category_cards, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :slug, :string, null: false

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :image_key, :string
      add :image_width, :integer
      add :image_height, :integer
      add :image_focal_x, :float, null: false, default: 0.5
      add :image_focal_y, :float, null: false, default: 0.5
      add :image_alt, :text
      add :image_title, :string
      add :image_artist, :string
      add :image_year, :string
      add :image_source_url, :string
      add :image_license, :string
      add :image_updated_at, :utc_datetime
    end

    create unique_index(:category_cards, [:slug], name: "category_cards_unique_slug_index")

    create constraint(:category_cards, :image_focal_x_in_range,
             check: """
               image_focal_x >= 0.0 AND image_focal_x <= 1.0
             """
           )

    create constraint(:category_cards, :image_focal_y_in_range,
             check: """
               image_focal_y >= 0.0 AND image_focal_y <= 1.0
             """
           )

    alter table(:mysteries) do
      add :image_key, :string
      add :image_width, :integer
      add :image_height, :integer
      add :image_focal_x, :float, null: false, default: 0.5
      add :image_focal_y, :float, null: false, default: 0.5
      add :image_alt, :text
      add :image_title, :string
      add :image_artist, :string
      add :image_year, :string
      add :image_source_url, :string
      add :image_license, :string
      add :image_updated_at, :utc_datetime
    end

    create constraint(:mysteries, :image_focal_x_in_range,
             check: """
               image_focal_x >= 0.0 AND image_focal_x <= 1.0
             """
           )

    create constraint(:mysteries, :image_focal_y_in_range,
             check: """
               image_focal_y >= 0.0 AND image_focal_y <= 1.0
             """
           )
  end

  def down do
    drop_if_exists constraint(:mysteries, :image_focal_y_in_range)

    drop_if_exists constraint(:mysteries, :image_focal_x_in_range)

    alter table(:mysteries) do
      remove :image_updated_at
      remove :image_license
      remove :image_source_url
      remove :image_year
      remove :image_artist
      remove :image_title
      remove :image_alt
      remove :image_focal_y
      remove :image_focal_x
      remove :image_height
      remove :image_width
      remove :image_key
    end

    drop_if_exists constraint(:category_cards, :image_focal_y_in_range)

    drop_if_exists constraint(:category_cards, :image_focal_x_in_range)

    drop_if_exists unique_index(:category_cards, [:slug],
                     name: "category_cards_unique_slug_index"
                   )

    drop table(:category_cards)
  end
end
