defmodule LumenViae.Repo.Migrations.AddArtworkVariantWidths do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:authors) do
      add :image_variant_widths, {:array, :bigint}, null: false, default: []
    end

    alter table(:category_cards) do
      add :image_variant_widths, {:array, :bigint}, null: false, default: []
    end

    alter table(:meditation_sets) do
      add :image_variant_widths, {:array, :bigint}, null: false, default: []
    end

    alter table(:mysteries) do
      add :image_variant_widths, {:array, :bigint}, null: false, default: []
    end
  end

  def down do
    alter table(:mysteries) do
      remove :image_variant_widths
    end

    alter table(:meditation_sets) do
      remove :image_variant_widths
    end

    alter table(:category_cards) do
      remove :image_variant_widths
    end

    alter table(:authors) do
      remove :image_variant_widths
    end
  end
end
