defmodule LumenViae.Repo.Migrations.AddMeditationNarrationFilename do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:meditations) do
      add :narration_filename, :text
    end
  end

  def down do
    alter table(:meditations) do
      remove :narration_filename
    end
  end
end
