defmodule LumenViae.Repo.Migrations.InstallAshRequiredFunction do
  @moduledoc """
  Brings Ash's SQL helper functions (`ash-functions`) from version 5 to 6,
  which adds `ash_required`.

  `initialize_extensions_1` was generated before the dependencies were
  brought up to date, so it stopped one version short and
  `mix ash_postgres.generate_migrations --check` reported this as pending.
  It creates a function and touches no table.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE OR REPLACE FUNCTION ash_required(value ANYCOMPATIBLE, payload jsonb)
    RETURNS ANYCOMPATIBLE AS $$
    BEGIN
      IF value IS NULL THEN
        RETURN ash_raise_error(payload, value);
      END IF;

      RETURN value;
    END;
    $$ LANGUAGE plpgsql
    STABLE
    SET search_path = '';
    """)
  end

  def down do
    # Uncomment this if you actually want to uninstall the extensions
    # when this migration is rolled back:
    execute("DROP FUNCTION IF EXISTS ash_required(ANYCOMPATIBLE, jsonb)")
  end
end
