defmodule LumenViae.Repo.Migrations.AddCompletionSetTimeIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:rosary_completions, [:meditation_set_id, :completed_at])
  end

  def down do
    drop_if_exists index(:rosary_completions, [:meditation_set_id, :completed_at])
  end
end
