defmodule LumenViae.Repo.Migrations.RecordVersionAdmin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:authors_versions) do
      add :admin_id,
          references(:admins,
            column: :id,
            name: "authors_versions_admin_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:meditation_sets_versions) do
      add :admin_id,
          references(:admins,
            column: :id,
            name: "meditation_sets_versions_admin_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:meditations_versions) do
      add :admin_id,
          references(:admins,
            column: :id,
            name: "meditations_versions_admin_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    alter table(:mysteries_versions) do
      add :admin_id,
          references(:admins,
            column: :id,
            name: "mysteries_versions_admin_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:mysteries_versions, "mysteries_versions_admin_id_fkey")

    alter table(:mysteries_versions) do
      remove :admin_id
    end

    drop constraint(:meditations_versions, "meditations_versions_admin_id_fkey")

    alter table(:meditations_versions) do
      remove :admin_id
    end

    drop constraint(:meditation_sets_versions, "meditation_sets_versions_admin_id_fkey")

    alter table(:meditation_sets_versions) do
      remove :admin_id
    end

    drop constraint(:authors_versions, "authors_versions_admin_id_fkey")

    alter table(:authors_versions) do
      remove :admin_id
    end
  end
end
