defmodule LumenViae.Repo.Migrations.AddMysteryMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mysteries) do
      add :fruit, :string
      add :key_verse, :text
      add :key_verse_reference, :string
    end
  end

  def down do
    alter table(:mysteries) do
      remove :key_verse_reference
      remove :key_verse
      remove :fruit
    end
  end
end
