defmodule LumenViaeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :lumen_viae

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `secure` is set in production only (config/prod.exs), so the browser
  # never sends the admin's cookie over plain HTTP; development serves plain
  # HTTP and would lose its session.
  @session_options [
    store: :cookie,
    key: "_lumen_viae_key",
    signing_salt: "4tFxwdp5",
    same_site: "Lax",
    secure: Application.compile_env(:lumen_viae, :secure_session_cookie, false)
  ]

  # `:x_headers` and `:peer_data` are what let a LiveView see who connected,
  # which the completion analytics need; `:user_agent` is what lets it tell
  # a crawler from a person.
  #
  # Note that `:x_headers` collects only headers beginning with `x-`, so
  # Fly's own `Fly-Client-IP` never reaches a socket and the address here
  # comes from `X-Forwarded-For`. `LumenViaeWeb.ClientIP` reads both and
  # takes whichever it is given.
  #
  # `compress: true` negotiates permessage-deflate, so the join reply (all
  # of a page's markup, as JSON) and every diff cross the wire deflated. A
  # browser that does not offer it is unaffected.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      compress: true,
      connect_info: [:peer_data, :x_headers, :user_agent, session: @session_options]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # `assets` is digested: the manifest rewrites its paths to a name that
  # changes with the file, and Plug.Static answers those with a year and
  # `immutable`. `images` and `fonts` are not digested, because pages name
  # them directly, so there is no name to bust and they cannot be cached for
  # a year. A week lets a returning visitor skip the round trip each file
  # used to cost (a `304` per image). The price is that a file replaced in
  # place under the same name reaches a returning visitor up to a week late,
  # so give a changed image a new name. The rest (favicon, robots.txt,
  # sitemap.xml) stays revalidated.
  plug Plug.Static,
    at: "/",
    from: :lumen_viae,
    gzip: not code_reloading?,
    cache_control_for_etags: "public, max-age=604800",
    only: ~w(images fonts)

  plug Plug.Static,
    at: "/",
    from: :lumen_viae,
    gzip: not code_reloading?,
    only: LumenViaeWeb.static_paths() -- ~w(images fonts)

  # Tidewave: an MCP server for coding agents at /tidewave/mcp, which runs
  # code and SQL inside this app. Development only - the dependency is not
  # compiled outside :dev, so the plug cannot reach a release. It answers
  # loopback requests only. See docs/DEV_TOOLS.md.
  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :lumen_viae
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  plug Plug.Telemetry,
    event_prefix: [:phoenix, :endpoint],
    log: {__MODULE__, :log_level, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json, Absinthe.Plug.Parser],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LumenViaeWeb.Router

  @doc """
  The request log's level for `conn`: none for `GET /healthz`, which a
  monitor asks every few seconds and would bury every other line; the
  default for everything else.
  """
  def log_level(%{path_info: ["healthz"]}), do: false
  def log_level(_conn), do: :info
end
