defmodule LumenViaeWeb.GraphqlSchema do
  @moduledoc """
  The GraphQL API, served at `/api/graphql`.

  Generated by AshGraphql from the domains listed here: every query and
  mutation is an Ash action, declared in its domain's `graphql` block, so
  validation and authorization are the domain's and not this module's.
  The REST API under `/api` is unaffected and stays the contract the iOS
  app is built on. See docs/GRAPHQL.md.
  """
  use Absinthe.Schema

  use AshGraphql,
    domains: [LumenViae.Office, LumenViae.Rosary]

  query do
  end

  mutation do
  end

  # The one public write is guarded like its REST twin: a crawler check
  # before the mutation resolves, and the action's own per-address rate limit
  # reported as a refusal of the request after it.
  def middleware(middleware, %{identifier: :record_completion}, %{identifier: :mutation}) do
    [{LumenViaeWeb.Graphql.GuardCompletions, :before} | middleware] ++
      [{LumenViaeWeb.Graphql.GuardCompletions, :after}]
  end

  def middleware(middleware, _field, _object), do: middleware
end
