defmodule LumenViaeWeb.GraphqlSchema do
  @moduledoc """
  The GraphQL API, served at `/api/graphql`.

  Generated by AshGraphql from the domains listed here: every query and
  mutation is an Ash action, declared in its domain's `graphql` block, so
  validation and authorization are the domain's and not this module's.
  The REST API under `/api` is unaffected and stays the contract the iOS
  app is built on. See docs/GRAPHQL.md.
  """
  use Absinthe.Schema

  use AshGraphql,
    domains: [LumenViae.Office, LumenViae.Rosary]

  query do
  end

  mutation do
  end
end
