defmodule LumenViaeWeb.JsonApiRouter do
  @moduledoc """
  The versioned REST API, served at `/api/v2` as JSON:API.

  Generated by AshJsonApi from the routes declared in `LumenViae.Rosary`'s
  `json_api` block: every route is an Ash action, so validation and
  authorization are the domain's and not this module's. The unversioned
  REST API under `/api` is unaffected and stays frozen for the builds
  already installed. See docs/JSON_API.md.

  The OpenAPI 3 document is generated by `spec/0`, corrected so that a
  generated client can call every route and decode every response (see
  `LumenViaeWeb.JsonApi.OpenApi`), and committed as `priv/openapi/v2.json`,
  which is what `/api/v2/open_api` serves (`LumenViaeWeb.JsonApi.Document`).
  """
  use AshJsonApi.Router,
    domains: [LumenViae.Rosary],
    open_api_title: "Lumen Viae API",
    open_api_version: "2.0.0",
    open_api_servers: ["https://www.lumenviae.org"],
    modify_open_api: {LumenViaeWeb.JsonApi.OpenApi, :modify, []},
    before_dispatch: {__MODULE__, :before_dispatch, []}

  @doc false
  # The completion write is the one route with a rate limit, and a refusal
  # says how long to wait, as REST's does.
  def before_dispatch(conn, %{route: %{action: :record_from_app}}) do
    LumenViaeWeb.Plugs.RetryAfter.call(conn, :completion)
  end

  def before_dispatch(conn, _route_info), do: conn
end
