defmodule LumenViaeWeb.JsonApiRouter do
  @moduledoc """
  The versioned REST API, served at `/api/v2` as JSON:API.

  Generated by AshJsonApi from the routes declared in `LumenViae.Rosary`'s
  `json_api` block: every route is an Ash action, so validation and
  authorization are the domain's and not this module's. The OpenAPI 3
  document is served at `/api/v2/open_api` and committed as
  `priv/openapi/v2.json`. The unversioned REST API under `/api` is
  unaffected and stays frozen for the builds already installed. See
  docs/JSON_API.md.

  The document is corrected before it is served or committed, so that a
  generated client can call every route and decode every response; see
  `LumenViaeWeb.JsonApi.OpenApi`.
  """
  use AshJsonApi.Router,
    domains: [LumenViae.Rosary],
    open_api: "/open_api",
    open_api_title: "Lumen Viae API",
    open_api_version: "2.0.0",
    open_api_servers: ["https://www.lumenviae.org"],
    modify_open_api: {LumenViaeWeb.JsonApi.OpenApi, :modify, []},
    before_dispatch: {__MODULE__, :before_dispatch, []}

  @doc false
  # AshJsonApi sends the OpenAPI document with no content type.
  def before_dispatch(conn, :open_api),
    do: Plug.Conn.put_resp_content_type(conn, "application/json")

  def before_dispatch(conn, _route_info), do: conn
end
