defmodule LumenViaeWeb.JsonApiRouter do
  @moduledoc """
  The versioned REST API, served at `/api/v2` as JSON:API.

  Generated by AshJsonApi from the routes declared in `LumenViae.Rosary`'s
  `json_api` block: every route is an Ash action, so validation and
  authorization are the domain's and not this module's. The unversioned
  REST API under `/api` is unaffected and stays frozen for the builds
  already installed. See docs/JSON_API.md.

  The OpenAPI 3 document is generated by `spec/0`, corrected so that a
  generated client can call every route and decode every response (see
  `LumenViaeWeb.JsonApi.OpenApi`), and committed as `priv/openapi/v2.json`,
  which is what `/api/v2/open_api` serves (`LumenViaeWeb.JsonApi.Document`).
  """
  use AshJsonApi.Router,
    domains: [LumenViae.Rosary],
    open_api_title: "Lumen Viae API",
    open_api_version: "2.0.0",
    open_api_servers: ["https://www.lumenviae.org"],
    modify_open_api: {LumenViaeWeb.JsonApi.OpenApi, :modify, []}
end
